name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: toysmoon/twidy_fe:latest
          
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-twidy-fe ]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker run
        run: |
          docker pull toysmoon/twidy_fe:lastest
          docker ps -q --filter "name=twidy_fe" | grep -q . && docker stop twidy_fe && docker rm -fv twidy_fe
          docker run -d -p 3000:3000 --name twidy_fe --restart always toysmoon/twidy_fe:latest
